name: mmex_server
description: A web server built using the shelf package.
version: 0.0.1
#homepage: https://www.example.com
#author: Igor Borges <igor@borges.me> <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: ^0.13.7
  shelf: ^0.6.0
  logging: ^0.11.3+1
  logging_handlers: ^0.8.0

#dev_dependencies:
#  test: ^0.12.0
